Because why would I wan the code-under-test to be accessible from the tests? That's pure madness right there.
> ReferenceError: rgbToHex is not defined